version: "3.3"
services:
    nginx:
        container_name: 'nginx'
        depends_on:
          - front
          - api
        restart: always # because it is routing traffic to our entire app....
        image: loaymoh99/dkr-dropoids-nginx
        volumes:
          #- ./nginx:/etc/nginx/conf.d
          - ./log/nginx:/var/log/nginx
        expose:
          - 443
        ports:
          - '80:80'
          - '443:443'

    api:
        image: loaymoh99/dkr-dropoids-api
        # ports:
        #     - 8080:8080
        restart: on-failure
        container_name: api
        # volumes:
        #   - ./../Team2_backend/src/photos:/app/src/photos
        #  - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    front:
        image: loaymoh99/dkr-dropoids-front
        # ports:
        #     - 8081:8081
        # volumes:
        #     - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
        restart: on-failure
        container_name: front

